<a href="https://colab.research.google.com/github/AmberFu/42_Rush_Numpy/blob/master/RUSH_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pfu

In [0]:
import numpy as np

np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
# 1. Create a matrix of random values of a distribution of your choice.
# np.random.rand(row, column)
np.random.rand(3,2)

array([[0.55579873, 0.68660805],
       [0.18162867, 0.58675911],
       [0.06913145, 0.88484724]])

In [0]:
# 2. Create a 1-dimensional array of 12 sequential numbers and convert it to a 4x3 array.
arr_1d = np.random.rand(12)
arr_2d = np.reshape(arr_1d, (4,3))
arr_2d

array([[0.52011903, 0.85006528, 0.68830658],
       [0.26460134, 0.58124694, 0.70975428],
       [0.99770853, 0.728203  , 0.19453587],
       [0.29666105, 0.87331205, 0.22039248]])

In [0]:
# 3. Write a function that creates an incremental N-dimensional (nd) array of dimension 
#    (1,n) with values between 0 and 1. Use arr.shape to verify
def nd_arr_from0to1(int n):
    return np.random.rand(1,n)

# 3. Write a function that creates an incremental N-dimensional (nd) array of dimension 
#    (1,n) with values between 0 and 1. Use arr.shape to verify
def nd_arr_from0to1(int n):
    return np.random.rand(1,n)

  nd_arr_from0to1(5)

SyntaxError: ignored

In [0]:
# 4. Generate a 10x12 array and extract row 0-4 of columns 8-12.


In [0]:
# 5. Using the function in Q3, get m vectors and bind them together (to have a m x n)
#    matrix. Plot the matrix with matplotlib’s imshow

